// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CFPcalculationRCPP
arma::mat CFPcalculationRCPP(arma::mat ef, arma::mat L, arma::mat FD);
RcppExport SEXP _Avionic24_CFPcalculationRCPP(SEXP efSEXP, SEXP LSEXP, SEXP FDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type ef(efSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type FD(FDSEXP);
    rcpp_result_gen = Rcpp::wrap(CFPcalculationRCPP(ef, L, FD));
    return rcpp_result_gen;
END_RCPP
}
// inversion_rcpp3
arma::mat inversion_rcpp3(arma::mat m1);
RcppExport SEXP _Avionic24_inversion_rcpp3(SEXP m1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type m1(m1SEXP);
    rcpp_result_gen = Rcpp::wrap(inversion_rcpp3(m1));
    return rcpp_result_gen;
END_RCPP
}
// Mult2_rcpp3
arma::mat Mult2_rcpp3(arma::mat matA, arma::mat matB);
RcppExport SEXP _Avionic24_Mult2_rcpp3(SEXP matASEXP, SEXP matBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type matA(matASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type matB(matBSEXP);
    rcpp_result_gen = Rcpp::wrap(Mult2_rcpp3(matA, matB));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Avionic24_CFPcalculationRCPP", (DL_FUNC) &_Avionic24_CFPcalculationRCPP, 3},
    {"_Avionic24_inversion_rcpp3", (DL_FUNC) &_Avionic24_inversion_rcpp3, 1},
    {"_Avionic24_Mult2_rcpp3", (DL_FUNC) &_Avionic24_Mult2_rcpp3, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Avionic24(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
