# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix Multiplication : 3 components
#'
#' This function returns the matrix multiplication of 3 matrix
#' as for footprint calculation
#'
#' @param ef matrix
#' @param L matrix
#' @param FD matrix
#' @export
CFPcalculationRCPP <- function(ef, L, FD) {
    .Call('_Avionic24_CFPcalculationRCPP', PACKAGE = 'Avionic24', ef, L, FD)
}

inversion_rcpp3 <- function(m1) {
    .Call('_Avionic24_inversion_rcpp3', PACKAGE = 'Avionic24', m1)
}

#' Matrix Multiplication : 2 components
#'
#' This function returns the matrix multiplication of 2 matrix
#'
#' @param matA matrix
#' @param matB matrix
#' @export
Mult2_rcpp3 <- function(matA, matB) {
    .Call('_Avionic24_Mult2_rcpp3', PACKAGE = 'Avionic24', matA, matB)
}

